name: Scrape and Store Data

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '5 10 * * *'
    - cron: '0 6 * * 0'
  workflow_dispatch:

env:
  MYSQL_HOST: 127.0.0.1
  MYSQL_DATABASE: wordpress_data
  MYSQL_USER: root
  MYSQL_PASSWORD: hritik1234

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest
    environment: production

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..15}; do
            if mysql -h127.0.0.1 -uroot -phritik1234 -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL is up and ready!"
              break
            fi
            echo "Waiting for MySQL... ($i/15)"
            sleep 5
          done

      - name: Recreate domains.json from GitHub secret
        run: |
          echo "$DOMAINS_JSON_B64" | base64 --decode > domains.json
        env:
          DOMAINS_JSON_B64: ${{ secrets.DOMAINS_JSON_B64 }}


      - name: Run the database migration
        run: python migrate_sqlite_to_mysql.py
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data

      - name: Run the scraper
        run: python fetch_data.py
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data
