name: Scrape and Store Data

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '5 10 * * *'
    - cron: '0 6 * * 0'
  workflow_dispatch:

env:
  MYSQL_HOST: localhost
  MYSQL_DATABASE: wordpress_data
  MYSQL_USER: root

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest
    environment: production

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data
          MYSQL_USER: root
          MYSQL_PASSWORD: hritik1234
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..5}; do
            if mysql -h127.0.0.1 -uroot -p"hritik1234" -e "SELECT 1 FROM wordpress_data.domains LIMIT 1"; then
              echo "MySQL is up and ready!"
              break
            fi
            echo "Waiting for MySQL... ($i/5)"
            sleep 5
          done


      - name: Run the database migration
        run: python migrate_sqlite_to_mysql.py
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data

      - name: Run the scraper
        run: python fetch_data.py
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: hritik1234
          MYSQL_DATABASE: wordpress_data
