name: Scrape and Store Data

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '5 10 * * *'
    - cron: '0 6 * * 0'
  workflow_dispatch:

env:
  MYSQL_HOST: 127.0.0.1
  MYSQL_DATABASE: wordpress_data
  MYSQL_USER: root

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest
    environment: production   # <-- Specify your environment name here

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..20}; do
            if mysql -h${{ env.MYSQL_HOST }} -u"${{ env.MYSQL_USER }}" -p"${{ secrets.MYSQL_PASSWORD }}" -e "SELECT 1" ${{ env.MYSQL_DATABASE }}; then
              echo "MySQL is up and ready!"
              break
            fi
            echo "Waiting for MySQL... ($i/20)"
            sleep 5
          done

      - name: Run the database migration
        run: python migrate_sqlite_to_mysql.py
        env:
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}

      - name: Run the scraper
        run: python fetch_data.py
        env:
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}